using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace JobPortalKCV.Helpers
{
    public static class UiText
    {
        public const string CookieName = "kcv_lang";

        private static readonly IDictionary<string, string> English = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Lang.English"] = "English",
            ["Lang.Vietnamese"] = "Tiếng Việt",
            ["Lang.Language"] = "Language",

            ["Nav.Home"] = "Home",
            ["Nav.FindJobs"] = "Find Jobs",
            ["Nav.Companies"] = "Companies",
            ["Nav.Candidates"] = "Candidates",
            ["Nav.Docs"] = "Docs",
            ["Nav.Contact"] = "Contact",
            ["Nav.AdminDashboard"] = "Admin Dashboard",
            ["Nav.BackToSite"] = "Back to Site",
            ["Nav.AccountSettings"] = "Account Settings",
            ["Nav.MyProfile"] = "My Profile",
            ["Nav.MyApplications"] = "My Applications",
            ["Nav.CVManagement"] = "CV Management",
            ["Nav.SavedItems"] = "Saved Items",
            ["Nav.Invitations"] = "Invitations",
            ["Nav.SentInvitations"] = "Sent Invitations",
            ["Nav.SavedCandidates"] = "Saved Candidates",
            ["Nav.ManageJobs"] = "Manage Jobs",
            ["Nav.Applications"] = "Applications",
            ["Nav.CompanySettings"] = "Company Settings",
            ["Nav.ManageUsers"] = "Manage Users",
            ["Nav.ManageCompanies"] = "Manage Companies",
            ["Nav.ManageApplications"] = "Manage Applications",
            ["Nav.ManageStars"] = "Manage Stars",
            ["Nav.SystemSettings"] = "System Settings",
            ["Nav.Notifications"] = "Notifications",

            ["Auth.Login"] = "Login",
            ["Auth.Register"] = "Register",
            ["Auth.Logout"] = "Logout",
            ["Auth.EmailOrUsername"] = "Email or username",
            ["Auth.Password"] = "Password",
            ["Auth.RememberMe"] = "Remember me",
            ["Auth.ForgotPassword"] = "Forgot password?",
            ["Auth.CreateAccount"] = "Create an account",
            ["Auth.VerifyEmail"] = "Verify email",
            ["Auth.ResetPassword"] = "Reset password",
            ["Auth.ForgotPasswordTitle"] = "Forgot Password",
            ["Auth.CreateAccountEyebrow"] = "Create account",
            ["Auth.ChooseAccountType"] = "Choose your account type",
            ["Auth.Candidate"] = "Candidate",
            ["Auth.Employer"] = "Employer",
            ["Auth.CandidateRegisterText"] = "Search jobs, save opportunities, and apply with your profile.",
            ["Auth.EmployerRegisterText"] = "Create a company profile, upload your logo, and post jobs.",
            ["Auth.RegisterAsCandidate"] = "Register as Candidate",
            ["Auth.RegisterAsEmployer"] = "Register as Employer",
            ["Auth.AlreadyHaveAccount"] = "Already have an account? Login",

            ["Button.Search"] = "Search",
            ["Button.Filter"] = "Filter",
            ["Button.Reset"] = "Reset",
            ["Button.Create"] = "Create",
            ["Button.Save"] = "Save",
            ["Button.SaveChanges"] = "Save Changes",
            ["Button.Delete"] = "Delete",
            ["Button.Edit"] = "Edit",
            ["Button.Details"] = "Details",
            ["Button.ViewDetails"] = "View Details",
            ["Button.Apply"] = "Apply",
            ["Button.PostJob"] = "Post a job",
            ["Button.BrowseAllJobs"] = "Browse All Jobs",
            ["Button.UploadCV"] = "Upload your CV",
            ["Button.UploadNewCV"] = "Upload new CV",
            ["Button.AddNewCompany"] = "Add new company",
            ["Button.Back"] = "Back",
            ["Button.BackToList"] = "Back to List",
            ["Button.Cancel"] = "Cancel",
            ["Button.Previous"] = "Previous",
            ["Button.Next"] = "Next",

            ["Home.Title"] = "Home",
            ["Home.HeroTitle"] = "Get hired by the right company.",
            ["Home.HeroSubtitle"] = "Find jobs, explore companies, and build your next career move from one clean portal.",
            ["Home.JobKeywordPlaceholder"] = "Job title or keyword",
            ["Home.AllLocations"] = "All locations",
            ["Home.JobCategories"] = "Job categories",
            ["Home.BrowseTopCategories"] = "Browse Top Categories",
            ["Home.ActiveJobsLine"] = "{0} active jobs from {1} companies",
            ["Home.ResumeHeadline"] = "Make your profile stand out with an online resume.",
            ["Home.EmployerCtaLine"] = "{0} active jobs are connecting candidates with {1} companies",
            ["Home.EmployerCtaHeadline"] = "Post a new job and manage your hiring pipeline from KCV Job Portal.",
            ["Home.RecentJobs"] = "Recent jobs",
            ["Home.FeaturedJobs"] = "Featured Jobs",
            ["Home.NoJobsAvailable"] = "No jobs available",
            ["Home.NoJobsHomeHint"] = "Create the first job posting to show it on the home page.",
            ["Home.ApplyProcess"] = "Apply process",
            ["Home.HowItWorks"] = "How it works",
            ["Home.StepSearchTitle"] = "1. Search a job",
            ["Home.StepSearchText"] = "Find roles by keyword, location, company, or category.",
            ["Home.StepApplyTitle"] = "2. Apply for job",
            ["Home.StepApplyText"] = "Open the job detail page and send your application.",
            ["Home.StepHiredTitle"] = "3. Get hired",
            ["Home.StepHiredText"] = "Track your next opportunity and connect with employers.",

            ["Jobs.Title"] = "Jobs",
            ["Jobs.RecentJobs"] = "Recent jobs",
            ["Jobs.FindNext"] = "Find your next opportunity",
            ["Jobs.Keyword"] = "Keyword",
            ["Jobs.AllCategories"] = "All categories",
            ["Jobs.AllLocations"] = "All locations",
            ["Jobs.AllSkills"] = "All skills",
            ["Jobs.Newest"] = "Newest",
            ["Jobs.Oldest"] = "Oldest",
            ["Jobs.MostStarred"] = "Most starred",
            ["Jobs.LeastStarred"] = "Least starred",
            ["Jobs.FoundCount"] = "{0} job(s) found",
            ["Jobs.NoJobsMatching"] = "There are no jobs matching the current filters.",
            ["Jobs.NotPosted"] = "Not posted",
            ["Jobs.StarsCount"] = "{0} star(s)",
            ["Jobs.Description"] = "Job Description",
            ["Jobs.NoDescription"] = "No description has been added for this job.",
            ["Jobs.RequiredSkills"] = "Required Skills",
            ["Jobs.NoSkills"] = "No skills have been listed for this job.",
            ["Jobs.Overview"] = "Job Overview",
            ["Jobs.PostedDate"] = "Posted date",
            ["Jobs.Location"] = "Location",
            ["Jobs.JobNature"] = "Job nature",
            ["Jobs.Salary"] = "Salary",
            ["Jobs.Deadline"] = "Deadline",
            ["Jobs.Stars"] = "Stars",
            ["Jobs.NotSet"] = "Not set",
            ["Jobs.ViewStarers"] = "View starers",
            ["Jobs.LoginToApply"] = "Login to apply",
            ["Jobs.SelectCv"] = "Select CV",
            ["Jobs.UseDefaultCv"] = "-- Use default CV --",
            ["Jobs.CoverLetter"] = "Cover letter",
            ["Jobs.ManageCvs"] = "Manage CVs",
            ["Jobs.ApplyNow"] = "Apply Now",
            ["Jobs.CandidateOnly"] = "Only candidate accounts can apply.",
            ["Jobs.CompanyInformation"] = "Company Information",
            ["Jobs.Name"] = "Name",
            ["Jobs.Web"] = "Web",
            ["Jobs.Email"] = "Email",
            ["Jobs.EditJob"] = "Edit job",
            ["Jobs.BackToJobs"] = "Back to jobs",
            ["Jobs.UnstarJob"] = "Unstar job",
            ["Jobs.StarJob"] = "Star job",
            ["Jobs.Unstar"] = "Unstar",
            ["Jobs.Star"] = "Star",

            ["Footer.AboutUs"] = "About Us",
            ["Footer.AboutText"] = "KCV Job Portal connects candidates, employers, and hiring teams in one focused job portal.",
            ["Footer.ContactInfo"] = "Contact Info",
            ["Footer.Address"] = "Address: Can Tho City, Vietnam.",
            ["Footer.Phone"] = "Phone: 0941 318 143",
            ["Footer.Email"] = "Email: support@jobfinder.local",
            ["Footer.ImportantLinks"] = "Important Links",
            ["Footer.Copyright"] = "KCV Job Portal. All rights reserved.",

            ["Admin.Overview"] = "Overview",
            ["Admin.Dashboard"] = "Dashboard",
            ["Admin.CoreTables"] = "Core Tables",
            ["Admin.Companies"] = "Companies",
            ["Admin.Jobs"] = "Jobs",
            ["Admin.ProfilesCvs"] = "Profiles & CVs",
            ["Admin.Applications"] = "Applications",
            ["Admin.Engagement"] = "Engagement",
            ["Admin.System"] = "System",
            ["Admin.Logs"] = "Logs",
            ["Admin.Workspace"] = "Manage the KCV Job Portal workspace.",
            ["Admin.Menu"] = "Menu",
            ["Admin.Users"] = "Users",
            ["Admin.Roles"] = "Roles",
            ["Admin.UserRoles"] = "User Roles",
            ["Admin.UserSettings"] = "User Settings",
            ["Admin.CompanyUsers"] = "Company Users",
            ["Admin.CompanyJoinRequests"] = "Company Join Requests",
            ["Admin.JobCategories"] = "Job Categories",
            ["Admin.JobCategoryMap"] = "Job Category Map",
            ["Admin.JobSkills"] = "Job Skills",
            ["Admin.Skills"] = "Skills",
            ["Admin.EmploymentTypes"] = "Employment Types",
            ["Admin.Locations"] = "Locations",
            ["Admin.UserProfiles"] = "User Profiles",
            ["Admin.UserEducations"] = "User Educations",
            ["Admin.UserExperiences"] = "User Experiences",
            ["Admin.UserProjects"] = "User Projects",
            ["Admin.UserSkills"] = "User Skills",
            ["Admin.UserCVs"] = "User CVs",
            ["Admin.ApplicationStatuses"] = "Application Statuses",
            ["Admin.Interviews"] = "Interviews",
            ["Admin.CandidateInvitations"] = "Candidate Invitations",
            ["Admin.Stars"] = "Stars",
            ["Admin.SystemSettingsPage"] = "System Settings Page",
            ["Admin.SystemSettingsTable"] = "SystemSettings Table",
            ["Admin.UserVerifications"] = "User Verifications",
            ["Admin.LoginLogs"] = "Login Logs",
            ["Admin.ActivityLogs"] = "Activity Logs",

            ["Companies.Title"] = "Companies",
            ["Companies.Explore"] = "Explore companies",
            ["Companies.AddCompany"] = "Add company",
            ["Companies.KeywordPlaceholder"] = "Company, industry or keyword",
            ["Companies.AllIndustries"] = "All industries",
            ["Companies.AllLocations"] = "All locations",
            ["Companies.NameAsc"] = "Name A-Z",
            ["Companies.NameDesc"] = "Name Z-A",
            ["Companies.FoundCount"] = "{0} company(s) found",
            ["Companies.NoCompanies"] = "No companies available",
            ["Companies.NoCompaniesMatching"] = "No companies match the current filters.",
            ["Companies.UnstarCompany"] = "Unstar company",
            ["Companies.StarCompany"] = "Star company",
            ["Companies.EditCompany"] = "Edit company",
            ["Companies.DeleteCompany"] = "Delete company",

            ["Message.NoRecords"] = "No records found.",
            ["Message.NoNotifications"] = "No notifications yet.",
            ["Message.SeeAllNotifications"] = "See all notifications",
            ["Message.PageOfRecords"] = "Page {0} of {1} ({2} record(s))",
            ["Message.SomethingWrong"] = "Something went wrong. Please try again.",
            ["Message.PasswordChanged"] = "Password changed successfully.",
            ["Message.SettingsUpdated"] = "Settings updated successfully.",
            ["Message.ApplicationSubmitted"] = "Application submitted successfully.",
            ["Error.AccessDenied"] = "You are not allowed to access this page.",
            ["Error.InvalidFile"] = "Invalid file format. Please upload a valid file.",
            ["Error.FileTooLarge"] = "File size exceeds the allowed limit.",
            ["Error.UploadCvBeforeApply"] = "Please upload your CV before applying."
        };

        private static readonly IDictionary<string, string> Vietnamese = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["Lang.English"] = "English",
            ["Lang.Vietnamese"] = "Tiếng Việt",
            ["Lang.Language"] = "Ngôn ngữ",

            ["Nav.Home"] = "Trang chủ",
            ["Nav.FindJobs"] = "Tìm việc",
            ["Nav.Companies"] = "Công ty",
            ["Nav.Candidates"] = "Ứng viên",
            ["Nav.Docs"] = "Tài liệu",
            ["Nav.Contact"] = "Liên hệ",
            ["Nav.AdminDashboard"] = "Bảng điều khiển Admin",
            ["Nav.BackToSite"] = "Quay lại website",
            ["Nav.AccountSettings"] = "Cài đặt tài khoản",
            ["Nav.MyProfile"] = "Hồ sơ của tôi",
            ["Nav.MyApplications"] = "Đơn ứng tuyển của tôi",
            ["Nav.CVManagement"] = "Quản lý CV",
            ["Nav.SavedItems"] = "Đã lưu",
            ["Nav.Invitations"] = "Lời mời",
            ["Nav.SentInvitations"] = "Lời mời đã gửi",
            ["Nav.SavedCandidates"] = "Ứng viên đã lưu",
            ["Nav.ManageJobs"] = "Quản lý tin tuyển dụng",
            ["Nav.Applications"] = "Đơn ứng tuyển",
            ["Nav.CompanySettings"] = "Cài đặt công ty",
            ["Nav.ManageUsers"] = "Quản lý người dùng",
            ["Nav.ManageCompanies"] = "Quản lý công ty",
            ["Nav.ManageApplications"] = "Quản lý đơn ứng tuyển",
            ["Nav.ManageStars"] = "Quản lý đánh dấu",
            ["Nav.SystemSettings"] = "Cấu hình hệ thống",
            ["Nav.Notifications"] = "Thông báo",

            ["Auth.Login"] = "Đăng nhập",
            ["Auth.Register"] = "Đăng ký",
            ["Auth.Logout"] = "Đăng xuất",
            ["Auth.EmailOrUsername"] = "Email hoặc tên đăng nhập",
            ["Auth.Password"] = "Mật khẩu",
            ["Auth.RememberMe"] = "Ghi nhớ tôi",
            ["Auth.ForgotPassword"] = "Quên mật khẩu?",
            ["Auth.CreateAccount"] = "Tạo tài khoản",
            ["Auth.VerifyEmail"] = "Xác thực email",
            ["Auth.ResetPassword"] = "Đặt lại mật khẩu",
            ["Auth.ForgotPasswordTitle"] = "Quên mật khẩu",
            ["Auth.CreateAccountEyebrow"] = "Tạo tài khoản",
            ["Auth.ChooseAccountType"] = "Chọn loại tài khoản",
            ["Auth.Candidate"] = "Ứng viên",
            ["Auth.Employer"] = "Nhà tuyển dụng",
            ["Auth.CandidateRegisterText"] = "Tìm việc, lưu cơ hội và ứng tuyển bằng hồ sơ của bạn.",
            ["Auth.EmployerRegisterText"] = "Tạo hồ sơ công ty, tải logo lên và đăng tin tuyển dụng.",
            ["Auth.RegisterAsCandidate"] = "Đăng ký ứng viên",
            ["Auth.RegisterAsEmployer"] = "Đăng ký nhà tuyển dụng",
            ["Auth.AlreadyHaveAccount"] = "Đã có tài khoản? Đăng nhập",

            ["Button.Search"] = "Tìm kiếm",
            ["Button.Filter"] = "Lọc",
            ["Button.Reset"] = "Đặt lại",
            ["Button.Create"] = "Tạo mới",
            ["Button.Save"] = "Lưu",
            ["Button.SaveChanges"] = "Lưu thay đổi",
            ["Button.Delete"] = "Xóa",
            ["Button.Edit"] = "Chỉnh sửa",
            ["Button.Details"] = "Chi tiết",
            ["Button.ViewDetails"] = "Xem chi tiết",
            ["Button.Apply"] = "Ứng tuyển",
            ["Button.PostJob"] = "Đăng tuyển",
            ["Button.BrowseAllJobs"] = "Xem tất cả việc làm",
            ["Button.UploadCV"] = "Tải CV lên",
            ["Button.UploadNewCV"] = "Tải CV mới lên",
            ["Button.AddNewCompany"] = "Thêm công ty mới",
            ["Button.Back"] = "Quay lại",
            ["Button.BackToList"] = "Quay lại danh sách",
            ["Button.Cancel"] = "Hủy",
            ["Button.Previous"] = "Trước",
            ["Button.Next"] = "Tiếp theo",

            ["Home.Title"] = "Trang chủ",
            ["Home.HeroTitle"] = "Tìm đúng công ty để phát triển sự nghiệp.",
            ["Home.HeroSubtitle"] = "Tìm việc, khám phá công ty và xây dựng bước tiến nghề nghiệp tiếp theo trong một cổng thông tin gọn gàng.",
            ["Home.JobKeywordPlaceholder"] = "Chức danh hoặc từ khóa",
            ["Home.AllLocations"] = "Tất cả địa điểm",
            ["Home.JobCategories"] = "Danh mục việc làm",
            ["Home.BrowseTopCategories"] = "Khám phá danh mục nổi bật",
            ["Home.ActiveJobsLine"] = "{0} việc làm đang mở từ {1} công ty",
            ["Home.ResumeHeadline"] = "Làm hồ sơ của bạn nổi bật hơn với CV trực tuyến.",
            ["Home.EmployerCtaLine"] = "{0} việc làm đang kết nối ứng viên với {1} công ty",
            ["Home.EmployerCtaHeadline"] = "Đăng việc làm mới và quản lý quy trình tuyển dụng trên KCV Job Portal.",
            ["Home.RecentJobs"] = "Việc làm mới",
            ["Home.FeaturedJobs"] = "Việc làm nổi bật",
            ["Home.NoJobsAvailable"] = "Chưa có việc làm",
            ["Home.NoJobsHomeHint"] = "Tạo tin tuyển dụng đầu tiên để hiển thị trên trang chủ.",
            ["Home.ApplyProcess"] = "Quy trình ứng tuyển",
            ["Home.HowItWorks"] = "Cách hoạt động",
            ["Home.StepSearchTitle"] = "1. Tìm việc",
            ["Home.StepSearchText"] = "Tìm vai trò theo từ khóa, địa điểm, công ty hoặc danh mục.",
            ["Home.StepApplyTitle"] = "2. Ứng tuyển",
            ["Home.StepApplyText"] = "Mở trang chi tiết việc làm và gửi đơn ứng tuyển.",
            ["Home.StepHiredTitle"] = "3. Nhận cơ hội",
            ["Home.StepHiredText"] = "Theo dõi cơ hội tiếp theo và kết nối với nhà tuyển dụng.",

            ["Jobs.Title"] = "Việc làm",
            ["Jobs.RecentJobs"] = "Việc làm mới",
            ["Jobs.FindNext"] = "Tìm cơ hội tiếp theo của bạn",
            ["Jobs.Keyword"] = "Từ khóa",
            ["Jobs.AllCategories"] = "Tất cả danh mục",
            ["Jobs.AllLocations"] = "Tất cả địa điểm",
            ["Jobs.AllSkills"] = "Tất cả kỹ năng",
            ["Jobs.Newest"] = "Mới nhất",
            ["Jobs.Oldest"] = "Cũ nhất",
            ["Jobs.MostStarred"] = "Được lưu nhiều nhất",
            ["Jobs.LeastStarred"] = "Được lưu ít nhất",
            ["Jobs.FoundCount"] = "Tìm thấy {0} việc làm",
            ["Jobs.NoJobsMatching"] = "Không có việc làm phù hợp với bộ lọc hiện tại.",
            ["Jobs.NotPosted"] = "Chưa đăng",
            ["Jobs.StarsCount"] = "{0} lượt lưu",
            ["Jobs.Description"] = "Mô tả công việc",
            ["Jobs.NoDescription"] = "Chưa có mô tả cho việc làm này.",
            ["Jobs.RequiredSkills"] = "Kỹ năng yêu cầu",
            ["Jobs.NoSkills"] = "Chưa có kỹ năng nào được liệt kê cho việc làm này.",
            ["Jobs.Overview"] = "Tổng quan việc làm",
            ["Jobs.PostedDate"] = "Ngày đăng",
            ["Jobs.Location"] = "Địa điểm",
            ["Jobs.JobNature"] = "Hình thức",
            ["Jobs.Salary"] = "Mức lương",
            ["Jobs.Deadline"] = "Hạn ứng tuyển",
            ["Jobs.Stars"] = "Lượt lưu",
            ["Jobs.NotSet"] = "Chưa đặt",
            ["Jobs.ViewStarers"] = "Xem người đã lưu",
            ["Jobs.LoginToApply"] = "Đăng nhập để ứng tuyển",
            ["Jobs.SelectCv"] = "Chọn CV",
            ["Jobs.UseDefaultCv"] = "-- Dùng CV mặc định --",
            ["Jobs.CoverLetter"] = "Thư ứng tuyển",
            ["Jobs.ManageCvs"] = "Quản lý CV",
            ["Jobs.ApplyNow"] = "Ứng tuyển ngay",
            ["Jobs.CandidateOnly"] = "Chỉ tài khoản ứng viên mới có thể ứng tuyển.",
            ["Jobs.CompanyInformation"] = "Thông tin công ty",
            ["Jobs.Name"] = "Tên",
            ["Jobs.Web"] = "Website",
            ["Jobs.Email"] = "Email",
            ["Jobs.EditJob"] = "Chỉnh sửa việc làm",
            ["Jobs.BackToJobs"] = "Quay lại danh sách việc làm",
            ["Jobs.UnstarJob"] = "Bỏ lưu việc làm",
            ["Jobs.StarJob"] = "Lưu việc làm",
            ["Jobs.Unstar"] = "Bỏ lưu",
            ["Jobs.Star"] = "Lưu",

            ["Footer.AboutUs"] = "Về chúng tôi",
            ["Footer.AboutText"] = "KCV Job Portal kết nối ứng viên, nhà tuyển dụng và đội ngũ tuyển dụng trong một cổng việc làm tập trung.",
            ["Footer.ContactInfo"] = "Thông tin liên hệ",
            ["Footer.Address"] = "Địa chỉ: Thành phố Cần Thơ, Việt Nam.",
            ["Footer.Phone"] = "Điện thoại: 0941 318 143",
            ["Footer.Email"] = "Email: support@jobfinder.local",
            ["Footer.ImportantLinks"] = "Liên kết quan trọng",
            ["Footer.Copyright"] = "KCV Job Portal. Bảo lưu mọi quyền.",

            ["Admin.Overview"] = "Tổng quan",
            ["Admin.Dashboard"] = "Bảng điều khiển",
            ["Admin.CoreTables"] = "Bảng cốt lõi",
            ["Admin.Companies"] = "Công ty",
            ["Admin.Jobs"] = "Việc làm",
            ["Admin.ProfilesCvs"] = "Hồ sơ & CV",
            ["Admin.Applications"] = "Ứng tuyển",
            ["Admin.Engagement"] = "Tương tác",
            ["Admin.System"] = "Hệ thống",
            ["Admin.Logs"] = "Nhật ký",
            ["Admin.Workspace"] = "Quản lý không gian làm việc KCV Job Portal.",
            ["Admin.Menu"] = "Menu",
            ["Admin.Users"] = "Người dùng",
            ["Admin.Roles"] = "Vai trò",
            ["Admin.UserRoles"] = "Vai trò người dùng",
            ["Admin.UserSettings"] = "Cài đặt người dùng",
            ["Admin.CompanyUsers"] = "Người dùng công ty",
            ["Admin.CompanyJoinRequests"] = "Yêu cầu tham gia công ty",
            ["Admin.JobCategories"] = "Danh mục việc làm",
            ["Admin.JobCategoryMap"] = "Liên kết danh mục việc làm",
            ["Admin.JobSkills"] = "Kỹ năng việc làm",
            ["Admin.Skills"] = "Kỹ năng",
            ["Admin.EmploymentTypes"] = "Hình thức làm việc",
            ["Admin.Locations"] = "Địa điểm",
            ["Admin.UserProfiles"] = "Hồ sơ người dùng",
            ["Admin.UserEducations"] = "Học vấn người dùng",
            ["Admin.UserExperiences"] = "Kinh nghiệm người dùng",
            ["Admin.UserProjects"] = "Dự án người dùng",
            ["Admin.UserSkills"] = "Kỹ năng người dùng",
            ["Admin.UserCVs"] = "CV người dùng",
            ["Admin.ApplicationStatuses"] = "Trạng thái ứng tuyển",
            ["Admin.Interviews"] = "Phỏng vấn",
            ["Admin.CandidateInvitations"] = "Lời mời ứng viên",
            ["Admin.Stars"] = "Đánh dấu",
            ["Admin.SystemSettingsPage"] = "Trang cấu hình hệ thống",
            ["Admin.SystemSettingsTable"] = "Bảng cấu hình hệ thống",
            ["Admin.UserVerifications"] = "Xác thực người dùng",
            ["Admin.LoginLogs"] = "Nhật ký đăng nhập",
            ["Admin.ActivityLogs"] = "Nhật ký hoạt động",

            ["Companies.Title"] = "Công ty",
            ["Companies.Explore"] = "Khám phá công ty",
            ["Companies.AddCompany"] = "Thêm công ty",
            ["Companies.KeywordPlaceholder"] = "Công ty, ngành hoặc từ khóa",
            ["Companies.AllIndustries"] = "Tất cả ngành",
            ["Companies.AllLocations"] = "Tất cả địa điểm",
            ["Companies.NameAsc"] = "Tên A-Z",
            ["Companies.NameDesc"] = "Tên Z-A",
            ["Companies.FoundCount"] = "Tìm thấy {0} công ty",
            ["Companies.NoCompanies"] = "Chưa có công ty",
            ["Companies.NoCompaniesMatching"] = "Không có công ty phù hợp với bộ lọc hiện tại.",
            ["Companies.UnstarCompany"] = "Bỏ lưu công ty",
            ["Companies.StarCompany"] = "Lưu công ty",
            ["Companies.EditCompany"] = "Chỉnh sửa công ty",
            ["Companies.DeleteCompany"] = "Xóa công ty",

            ["Message.NoRecords"] = "Không tìm thấy dữ liệu.",
            ["Message.NoNotifications"] = "Chưa có thông báo.",
            ["Message.SeeAllNotifications"] = "Xem tất cả thông báo",
            ["Message.PageOfRecords"] = "Trang {0} / {1} ({2} bản ghi)",
            ["Message.SomethingWrong"] = "Đã xảy ra lỗi. Vui lòng thử lại.",
            ["Message.PasswordChanged"] = "Đổi mật khẩu thành công.",
            ["Message.SettingsUpdated"] = "Cập nhật cài đặt thành công.",
            ["Message.ApplicationSubmitted"] = "Gửi đơn ứng tuyển thành công.",
            ["Error.AccessDenied"] = "Bạn không có quyền truy cập trang này.",
            ["Error.InvalidFile"] = "Định dạng tệp không hợp lệ. Vui lòng tải lên tệp hợp lệ.",
            ["Error.FileTooLarge"] = "Dung lượng tệp vượt quá giới hạn cho phép.",
            ["Error.UploadCvBeforeApply"] = "Vui lòng tải CV lên trước khi ứng tuyển."
        };

        public static string CurrentLanguage
        {
            get { return NormalizeLanguage(HttpContext.Current == null ? null : HttpContext.Current.Request.QueryString["lang"] ?? GetCookieLanguage()); }
        }

        public static string T(string key)
        {
            return T(key, CurrentLanguage);
        }

        public static string T(string key, params object[] args)
        {
            return String.Format(T(key), args);
        }

        public static string T(string key, string language)
        {
            string text;
            if (NormalizeLanguage(language) == "vi" && Vietnamese.TryGetValue(key, out text))
            {
                return text;
            }

            if (English.TryGetValue(key, out text))
            {
                return text;
            }

            return key;
        }

        public static string NormalizeLanguage(string language)
        {
            return String.Equals(language, "vi", StringComparison.OrdinalIgnoreCase) ? "vi" : "en";
        }

        public static IHtmlString T(this HtmlHelper html, string key)
        {
            return new HtmlString(HttpUtility.HtmlEncode(T(key)));
        }

        public static string SwitchUrl(UrlHelper url, string language, string returnUrl)
        {
            return url.Action("Set", "Language", new { lang = NormalizeLanguage(language), returnUrl = returnUrl ?? "/" });
        }

        private static string GetCookieLanguage()
        {
            var cookie = HttpContext.Current == null ? null : HttpContext.Current.Request.Cookies[CookieName];
            return cookie == null ? null : cookie.Value;
        }
    }
}
